Resource management
TeiaLabs/tauth pull request #27
Opened 2024-11-13 17:32 UTC by FHaggs

2024-11-13 18:55 UTC, martinduartemore requested changes

2024-11-13 18:55 UTC, martinduartemore commented on resources/policies/datasources.rego
> +admin_resources := _filter_resource("ds-admin:")
Let's use `::` as a separator. Example: `ds::admin::`.

We could use a policy with a function `build_permission_name(name_list)` that automatically builds a string using the separator. Then, all policies that need to build permission names can import this function from that policy. Example: `build_permission_name(["ds", "admin", "read-ID"]) = ds::admin::read-ID`.

2024-11-13 18:55 UTC, martinduartemore commented on tauth/dependencies/__init__.py
> +    authorization.setup_engine()
Reflect this change in docs.

2024-11-13 18:55 UTC, martinduartemore commented on tauth/entities/routes.py
> +                detail=f"Role {permission.name!r} already attached to entity {entity.handle!r}.",
Role -> Permission.

2024-11-13 18:55 UTC, martinduartemore commented on tauth/entities/routes.py
> +        "msg": "Role removed from entity.",
Role -> Permission.

2024-11-13 18:55 UTC, martinduartemore commented on tauth/resource_management/access/models.py
> +        return "resource-access"
`resource-accesses`

2024-11-13 18:55 UTC, martinduartemore commented on tauth/resource_management/access/routes.py
> +    infostar: Infostar = Depends(privileges.is_valid_user),
Use `Annotated`.

2024-11-13 18:55 UTC, martinduartemore commented on tauth/resource_management/resources/schemas.py
> +    )
Let's use FastAPI's `Example` class for this.

2024-11-13 18:55 UTC, martinduartemore commented on tauth/utils/fastapi_extension.py
Can we delete this file? :ninja:

2024-11-13 18:55 UTC, martinduartemore commented on tauth/utils/headers.py
HNNNGGGGGG :biting_lip: :hot_face: :sweat_drops:

2024-11-14 14:23 UTC, FHaggs commented on resources/policies/datasources.rego
> +admin_resources := _filter_resource("ds-admin:")
done

2024-11-14 17:17 UTC, martinduartemore approved these changes

2024-11-14 17:17 UTC, martinduartemore commented on resources/policies/datasources.rego
:goat:

2024-11-14 17:17 UTC, martinduartemore commented on resources/policies/utils.rego
:ok_hand:

2024-11-14 17:18 UTC, merged